# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: argo-app-pari
# spec:
#   source:
#     repoURL: 'https://github.com/parinithaopsera456/java-repo-pg.git'
#     path: 'sample'   # Update this if necessary to point to a valid directory in your repo
#     targetRevision: HEAD
#   destination:
#     server: 'https://kubernetes.default.svc'
#     namespace: 'samnamespcpari'

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: 8083-nexus-tecdmwng.ldapowner.opsera.io/test-repo-pari/dockerfile:11
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

