apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
images:
- name: the-my-app
  newName: 792373136340.dkr.ecr.us-west-1.amazonaws.com/nlpecrnew
  newTag: finaltag
