apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: myappkustom456
      labels:
        app: myappkustom456
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: myappkustom456
      template:
        metadata:
          labels:
            app: myapp4kusom56
        spec:
          containers:
          - name: my-app-container
            image: 792373136340.dkr.ecr.us-east-1.amazonaws.com/nlpecrnew:latest
            ports:
            - containerPort: 8080
            resources:
              requests:
                memory: "256Mi"
                cpu: "250m"
              limits:
                memory: "512Mi"
                cpu: "500m"
            livenessProbe:
              httpGet:
                path: /healthz
                port: 8080
              initialDelaySeconds: 30
              periodSeconds: 10
            readinessProbe:
              httpGet:
                path: /ready
                port: 8080
              initialDelaySeconds: 5
              periodSeconds: 10
  - |
    apiVersion: v1
    kind: Service
    metadata:
      name: my-app-service
    spec:
      selector:
        app: myappkustom456
      ports:
      - protocol: TCP
        port: 80
        targetPort: 8080
