apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: myappkustom456  # Ensure this matches the deployment labels
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
