# .github/workflows/ci.yml

name: Java CI Workflow

# Triggers the workflow on push to main branch and allows manual trigger using workflow_dispatch
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt' # Options: adopt, zulu, corretto, temurin, liberica

      # Cache Maven dependencies to improve build speed
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # Run Maven build and tests
      - name: Build with Maven
        run: mvn clean install

      # Optional: Upload test results or build artifacts if necessary
      - name: Archive build artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: java-build
          path: target/

  # Add a second job for deployment or other tasks as necessary
